# Read the documentation: https://github.com/acseo/TypesenseBundle/blob/master/README.md
acseo_typesense:
  typesense:
    url: '%env(resolve:TYPESENSE_URL)%'
    key: '%env(resolve:TYPESENSE_KEY)%'
    # Optional : add prefix to all collection names in Typesense
    #collection_prefix: 'app_'
  # Collection settings
  collections:
    article:
      entity: 'App\Entity\Article'
      fields:
        id:
          name: id
          type: primary

        sortable_id:
          entity_attribute: id             # Entity attribute name forced
          name: sortable_id                # Typesense field name
          type: int32
        title:
          name: title
          type: string
        shortTitle:
          name: shortTitle
          type: string
        category.name:
          name: category_name
          type: string
          facet: true
          entity_attribute: categorie.name
        text:
          name: text
          type: string
        author:
          name: author
          type: string
        createdAt:
          name: createAt
          type: datetime
          optional: true
      default_sorting_field: sortable_id       # Default sorting field. Must be int32 or float
      symbols_to_index: [ '+' ]