vich_uploader:
    db_driver: orm

    mappings:
        article:
            uri_prefix: /images/article
            upload_destination: '%kernel.project_dir%/public/img/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
